name: Build
on:
  push:
    branches:
      - master
      - actions-test
env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  HOMEBREW_NO_INSTALL_CLEANUP: 1
jobs:
  core:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: cmake --build .